import Testing
import Foundation
@testable import QuotientCore

/// Generates docs/RESULTS.md. Only runs when QUOTIENT_RESULTS_PATH is set:
///   QUOTIENT_RESULTS_PATH=../docs/RESULTS.md swift test -c release --filter ResultsReport
/// so the numbers in the README are produced by the code, never typed by hand.
@Suite("ResultsReport") struct ResultsReportTests {
    @Test func generate() async throws {
        guard let path = ProcessInfo.processInfo.environment["QUOTIENT_RESULTS_PATH"] else { return }
        let trials = Int(ProcessInfo.processInfo.environment["QUOTIENT_TRIALS"] ?? "") ?? 200
        var md = "# Monte Carlo Results\n\nGenerated by `ResultsReportTests` on \(ISO8601DateFormatter().string(from: Date()).prefix(10)) with \(trials) paired trials per scenario, base seed \(MonteCarloConfiguration(parameters: .example).baseSeed), γ = 0.01, k = 1.0, rolling horizon 300 steps. The fixed-spread control is matched to the A-S spread at zero inventory using σ from a pilot run. All P&L in dollars on a $100.00 instrument with 1¢ ticks and 100-share lots. Session Sharpe = mean(ΔP&L)/sd(ΔP&L)·√steps (a per-session t-statistic, not annualised). Markouts are ticks per lot at 50 steps; negative = price moved against the fill.\n\n"
        md += "These are simulation results under stated assumptions. They are not evidence of real-market profitability.\n\n"
        for preset in ScenarioPreset.all() {
            let cfg = MonteCarloConfiguration(parameters: preset.parameters, trials: trials)
            let ladder = MonteCarloRunner.standardLadder(parameters: preset.parameters)
            let rep = await MonteCarloRunner.run(cfg, strategies: ladder)
            let fixed = ladder[0] as! FixedSpreadMarketMaker
            md += ReportGenerator.markdown(rep, title: preset.name, scenarioSummary: preset.summary + " Matched fixed half-spread: \(String(format: "%.2f", fixed.halfSpreadTicks)) ticks.")
            md += "\n"
        }
        try md.write(toFile: path, atomically: true, encoding: .utf8)
        print("wrote \(path)")
    }
}
